name: tenka_store_template
description: Template for Tenka store
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    sora_builder:
        git:
            url: https://github.com/yukino-org/sora.git
            path: packages/sora_builder
    tenka:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka
    tenka_dev_tools:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka_dev_tools

dev_dependencies:
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
